<?php
session_start();
include('config.php');

// Enable error reporting for debugging (remove in production)
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Validate required parameters
if (!isset($_SESSION['user'])) {
    header('location:index.php');
    exit();
}

// Get the show ID from GET parameter if available
if (isset($_GET['show'])) {
    $_SESSION['show'] = $_GET['show'];
}

// Check if we have all required parameters
if (!isset($_GET['screen']) || !isset($_GET['date']) || !isset($_SESSION['show'])) {
    header('location:index.php?error=missing_parameters');
    exit();
}

// Store booking details in session
$_SESSION['screen'] = $_GET['screen'];
$_SESSION['date'] = $_GET['date'];

// Get screen details
$screen_id = $_GET['screen'];
$screen_query = mysqli_query($con, "SELECT * FROM tbl_screens WHERE screen_id='$screen_id'");
$screen = mysqli_fetch_array($screen_query);

if (!$screen) {
    header('location:index.php?error=invalid_screen');
    exit();
}

// Get show details to validate date
$show_query = mysqli_query($con, "SELECT * FROM tbl_shows WHERE s_id='" . $_SESSION['show'] . "'");
$show = mysqli_fetch_array($show_query);

if (!$show) {
    header('location:index.php?error=invalid_show');
    exit();
}

$date = $_GET['date'];
// Instead of strict validation, let's be more flexible
if (isset($show['start_date']) && isset($show['end_date'])) {
    // Only validate if both dates are present
    if (strtotime($date) < strtotime($show['start_date']) || strtotime($date) > strtotime($show['end_date'])) {
        // If invalid, set date to start date instead of error redirect
        $date = $show['start_date'];
        $_GET['date'] = $date; // Update GET parameter
    }
}

// Get already booked seats for this show
// Modified this query to check if seat_numbers column exists first
$bookedSeatsList = [];

// First, check if seat_numbers column exists
$columns_query = mysqli_query($con, "SHOW COLUMNS FROM tbl_bookings LIKE 'seat_numbers'");
if (mysqli_num_rows($columns_query) > 0) {
    // If column exists, use it
    $booked_query = mysqli_query($con, "SELECT seat_numbers FROM tbl_bookings WHERE show_id='".$_SESSION['show']."' AND ticket_date='".$_GET['date']."'");
    
    while ($booking = mysqli_fetch_array($booked_query)) {
        if (!empty($booking['seat_numbers'])) {
            $seats = json_decode($booking['seat_numbers'], true);
            if (is_array($seats)) {
                $bookedSeatsList = array_merge($bookedSeatsList, $seats);
            }
        }
    }
} else {
    // If seat_numbers column doesn't exist, try alternative approach
    // This is a fallback - we'll assume no specific seats are booked
    // You may need to modify this according to your actual database structure
    $bookedSeatsList = [];
}

// Include header after processing to ensure session variables are set
include('header.php');
?>

<div class="content">
    <div class="wrap">
        <div class="content-top">
            <h3 class="text-center">Select Your Seats</h3>
            
            <?php
            // Get movie information to display
            $movie_query = mysqli_query($con, "SELECT * FROM tbl_movie WHERE movie_id='" . $_SESSION['movie'] . "'");
            $movie = mysqli_fetch_array($movie_query);
            
            if ($movie) {
            ?>
            <div class="movie-info text-center" style="margin-bottom: 20px;">
                <h4><?php echo $movie['movie_name']; ?></h4>
                <p>Date: <?php echo date('d-M-Y', strtotime($_GET['date'])); ?></p>
            </div>
            <?php } ?>
            
            <form action="process_booking.php" method="post" id="seatForm">
                <div class="seat-map-container">
                    <div class="screen">SCREEN</div>
                    
                    <div class="seat-rows" id="seatMap">
                        <!-- Seat rows will be generated by JavaScript -->
                    </div>
                    
                    <div class="seat-info">
                        <div class="seat-info-item">
                            <div class="seat-info-box seat-available"></div>
                            <span>Available</span>
                        </div>
                        <div class="seat-info-item">
                            <div class="seat-info-box seat-selected"></div>
                            <span>Selected</span>
                        </div>
                        <div class="seat-info-item">
                            <div class="seat-info-box seat-booked"></div>
                            <span>Booked</span>
                        </div>
                    </div>
                    
                    <div class="selected-seats-container">
                        <div class="selected-seats-text">Selected Seats: <span id="selectedSeatsText">None</span></div>
                        <div class="selected-seats-text">Total Seats: <span id="totalSeats">0</span></div>
                        <div class="selected-seats-text">Total Amount: Rs <span id="totalAmount">0</span></div>
                        
                        <!-- Hidden inputs for form submission -->
                        <input type="hidden" id="selectedSeatsInput" name="selectedSeats" value="">
                        <input type="hidden" id="seats" name="seats" value="0">
                        <input type="hidden" id="hm" name="amount" value="0">
                        <input type="hidden" name="date" value="<?php echo $_GET['date']; ?>">
                        <input type="hidden" name="screen" value="<?php echo $screen_id; ?>">
                        <input type="hidden" name="show" value="<?php echo $_SESSION['show']; ?>">
                        
                        <div style="margin-top: 20px;">
                            <button type="submit" class="btn btn-success payment-btn" id="confirmSeats" disabled>Proceed to Payment</button>
                            <a href="booking.php" class="btn btn-default" style="margin-left: 10px;">Back to Booking</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="clear"></div>
    </div>
</div>

<?php include('footer.php'); ?>

<style>
    .seat-map-container {
        margin: 20px auto;
        width: 100%;
        max-width: 600px;
        background-color: #f8f8f8;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    
    .screen {
        background-color: #333;
        color: white;
        text-align: center;
        padding: 15px;
        margin-bottom: 30px;
        border-radius: 5px;
        font-weight: bold;
        letter-spacing: 2px;
    }
    
    .seat-rows {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-bottom: 20px;
    }
    
    .seat-row {
        display: flex;
        justify-content: center;
        margin-bottom: 10px;
        width: 100%;
    }
    
    .row-label {
        width: 30px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: bold;
    }
    
    .seat {
        width: 30px;
        height: 30px;
        margin: 3px;
        border-radius: 5px;
        background-color: #4CAF50;
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: center;
        color: white;
        font-size: 12px;
        transition: all 0.2s;
    }
    
    .seat:hover {
        background-color: #3e8e41;
        transform: scale(1.1);
    }
    
    .seat.selected {
        background-color: #f44336;
        transform: scale(1.1);
    }
    
    .seat.booked {
        background-color: #cccccc;
        cursor: not-allowed;
    }
    
    .seat-info {
        display: flex;
        justify-content: center;
        margin: 30px 0 20px;
        flex-wrap: wrap;
    }
    
    .seat-info-item {
        display: flex;
        align-items: center;
        margin: 0 15px;
    }
    
    .seat-info-box {
        width: 20px;
        height: 20px;
        margin-right: 8px;
        border-radius: 4px;
    }
    
    .seat-available {
        background-color: #4CAF50;
    }
    
    .seat-selected {
        background-color: #f44336;
    }
    
    .seat-booked {
        background-color: #cccccc;
    }
    
    .selected-seats-container {
        margin-top: 20px;
        text-align: center;
        padding: 15px;
        background-color: #f0f0f0;
        border-radius: 5px;
    }
    
    .selected-seats-text {
        font-weight: bold;
        margin-bottom: 10px;
        font-size: 16px;
    }
    
    .payment-btn {
        background-color: #4CAF50;
        color: white;
        padding: 12px 25px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
        transition: all 0.3s;
    }
    
    .payment-btn:hover {
        background-color: #45a049;
        transform: translateY(-2px);
    }
    
    .payment-btn:disabled {
        background-color: #cccccc;
        cursor: not-allowed;
        transform: none;
    }
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Error handler to catch JS errors
    window.onerror = function(message, source, lineno, colno, error) {
        console.error("Error: ", message, "at", source, ":", lineno);
        return true;
    };
    
    // Configuration
    const rows = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];
    const seatsPerRow = 10;
    const bookedSeats = <?php echo json_encode($bookedSeatsList); ?>;
    const seatPrice = <?php echo $screen['charge']; ?>;
    
    console.log("Booked seats:", bookedSeats);
    console.log("Seat price:", seatPrice);
    console.log("Session show ID:", "<?php echo $_SESSION['show']; ?>");
    
    // DOM elements
    const seatMap = document.getElementById('seatMap');
    const selectedSeatsText = document.getElementById('selectedSeatsText');
    const totalSeatsEl = document.getElementById('totalSeats');
    const totalAmountEl = document.getElementById('totalAmount');
    const selectedSeatsInput = document.getElementById('selectedSeatsInput');
    const confirmButton = document.getElementById('confirmSeats');
    const seatsInput = document.getElementById('seats');
    const amountInput = document.getElementById('hm');
    
    // State
    let selectedSeats = [];
    
    // Generate seat map
    function generateSeatMap() {
        if (!seatMap) {
            console.error("Seat map element not found!");
            return;
        }
        
        seatMap.innerHTML = '';
        
        for (let i = 0; i < rows.length; i++) {
            const row = document.createElement('div');
            row.className = 'seat-row';
            
            // Create row label
            const rowLabel = document.createElement('div');
            rowLabel.className = 'row-label';
            rowLabel.textContent = rows[i];
            row.appendChild(rowLabel);
            
            // Create seats in this row
            for (let j = 1; j <= seatsPerRow; j++) {
                const seat = document.createElement('div');
                const seatId = `${rows[i]}${j}`;
                seat.className = 'seat';
                seat.id = seatId;
                seat.setAttribute('data-seat-id', seatId);
                seat.textContent = j;
                
                // Check if this seat is already booked
                if (bookedSeats && bookedSeats.includes(seatId)) {
                    seat.className += ' booked';
                } else {
                    seat.addEventListener('click', function() {
                        toggleSeat(seatId);
                    });
                }
                
                row.appendChild(seat);
            }
            
            seatMap.appendChild(row);
        }
    }
    
    // Toggle seat selection
    function toggleSeat(seatId) {
        const seat = document.getElementById(seatId);
        if (!seat) return;
        
        if (selectedSeats.includes(seatId)) {
            // Deselect seat
            selectedSeats = selectedSeats.filter(id => id !== seatId);
            seat.classList.remove('selected');
        } else {
            // Select seat
            selectedSeats.push(seatId);
            seat.classList.add('selected');
        }
        
        updateSelectionInfo();
    }
    
    // Update selection info
    function updateSelectionInfo() {
        if (selectedSeats.length === 0) {
            selectedSeatsText.textContent = 'None';
            confirmButton.disabled = true;
        } else {
            selectedSeatsText.textContent = selectedSeats.join(', ');
            confirmButton.disabled = false;
        }
        
        totalSeatsEl.textContent = selectedSeats.length;
        totalAmountEl.textContent = selectedSeats.length * seatPrice;
        
        // Update hidden inputs for form submission
        selectedSeatsInput.value = JSON.stringify(selectedSeats);
        seatsInput.value = selectedSeats.length;
        amountInput.value = selectedSeats.length * seatPrice;
    }
    
    // Initialize seat map
    generateSeatMap();
});
</script>